### ISSUE TITLE
Setting directory crashes rimpy LINUX

### ISSUE THREAD

**Issue by Theycallmeaslak** [rimpy-custom/RimPy#64]
Im using manjaro-xfce and im trying to get rimpy to recognize rimworld but it can't find it automatically as its on a secondary drive. I can't use the browse function to find the folder as that crashes rimpy. Possibly an incompatibility with xfce or thunar, although i did try nautilus too. Nor can i just paste or write the path directly into the textfield.

**Comment by rimpy-custom** [comment]
Provide RimPy log file

**Comment by rimpy-custom** [comment]
May you test with new RimPy pre-release?

**Comment by NBZion** [comment]
This issue is still present,here is my rimpy.log @rimpy-custom
[rimpy.log](https://github.com/rimpy-custom/RimPy/files/9228227/rimpy.log)

**Comment by gavrilobos** [comment]
Having the same Issue on Manjaro-XFCE 

However, I did manage to run it with sudo, and have previously set all file permissions to read+write

The auto-populate doesn't work and I had to copy-paste the directories for game-folder, config-folder and steam-mods due to the folder browser not showing hidden folders and having no option to turn on hidden folder view (steam is defaulted to /home/xxx/.local/share/Steam/... and config is /home/xxx/.config/unity3d/...) (you can copy-paste the folder absolute location in the location browser window, not in the RimPy main window)

Hope this helps!

--edit: I'm running the latest (1.2.6.25) linux (currently pre-release) version

**Comment by rimpy-custom** [comment]
Closing for now. Reopen if issue wasn't fixed with latest Linux build 1.2.6.28.
