### ISSUE TITLE
Check for updates crashes Rimpy

### ISSUE THREAD

**Issue by handicast** [rimpy-custom/RimPy#77]
Normally rimpy just freezes for a moment to check for updates, but now rimpy closes itself after a few seconds when checking for updates.

**Comment by alreShan** [comment]
I guess I found the reason.....
RimPy Crash is because of the mod which going to be [Check for updates] is no longer exist in Steam-Workshop.
This crash happens in 1.2.6.25 and 1.2.5.21 (haven't tested others version myself)

I have a mod here which was existed and available in Steam-Workshop, but it's gone now( maybe it's deleted by author? IDK). This mod is a CE-patch of [Kurin DELUXE](modid:2670355481)
[2778846505.zip](https://github.com/rimpy-custom/RimPy/files/9398392/2778846505.zip)
mod name: Kurin DELUX CE Patch
![image](https://user-images.githubusercontent.com/104878767/186041818-ec7f61d8-9ede-4819-a99c-512859308d84.png)


Put this file to the location:
\Steam\steamapps\common\RimWorld\Mods
and you should be able to see it in RimPy
Then try to [Check for updates], RimPy crash.
