### ISSUE TITLE
Question: Why is RimPy closed source?

### ISSUE THREAD

**Issue by nechtarg** [rimpy-custom/RimPy#79]
I honestly don't understand it because:
- It is free and therefore can't be pirated by self compiling.
- The Dev already uses GitHub to publish releases, so pushing the code wouldn't add to much time.
- Small issues could be replaced by pull requests.
- (Maybe) development would be faster 
So what am I missing, please feel free to enlighten me.

**Comment by rimpy-custom** [comment]
Is there a reason I need to discuss that? You give users smth for free but they want more and more... I do not feel that publishing code will make it better. I would say it may cause more troubles than fix issues. Atleast for now.

**Comment by Xevion** [comment]
If a user has reason to believe that a project would be made better by open sourcing, but you decline to provide reasoning and keep it closed source, then the user can only suspect potential secret, malicious reasons. So yes, in the eyes of your users, you should be open about your reason behind keeping a project closed source. Your reasonings don't need to be elaborate, they just need to be reasonable.

If 'free' is part of your closed-source reasoning, then polishing the project and releasing it under open source can open avenues for crowd-sourced funding. I'm certain many people in the community appreciate what your application does and would be willing to donate. But you will need to be transparent in order to encourage involvement.

But again, it's up to you. If you don't care, then you need not do anything, not even respond to this GitHub issue. Good luck on your endeavors.

**Comment by rimpy-custom** [comment]
You base your conclusions on your own opinion/on the opinion of a small group of people, while trying to pass it off as the opinion of the majority. I cannot and would not prove smth here, since my opinion is my opinion and there always be users that will not or do not want to understand it. Everytime such kind of dicussions appear they end up with nothing but wasted time for me and that person. I do not want this to continue and see no reason. They will come and go, that is fine. Idk why but some users think that dev owe smth to them. Like you do "this" so you have to do "that" too. Some of them get disappointed, some go mad when you ruin their believes.   They do not understand that dev owe nothing to them. Visit official game Discord server or check comments of any mods, you will notice a lot of such users.
I keep in mind how I want to see that project in future and believe that going open source may cause troubles, for the current moment. You do not know how hard that was to cut through the notion that mods can be sorted in other ways than just categorizing them into groups and still there are users that do not get that. There always be users that want to change smth "in better way", but sometimes that way is not better. If you go open source, then you have to discuss, prove smth to them. That is 
exhausting. I may be wrong on some parts, but for current moment I belive that working on project alone is more efficient in terms of time/results/mental health. But there are several devs that really wanted to help me and share my opinion, I have met them and I feel bad that rejected their help. 
For those who do not trust me and think there are malicious reasons, I would suggest to not use this software because I cannot prove you anything in that regard.

P. S. I cannot receive donations from users because of sanctions.

**Comment by Ashturian** [comment]
Going open source doesn't mean you don't have to justify your code-writing decisions to anyone, you'll always have full control of it. It'd just make it possible for it to be audited for malicious code. Nothing can stop you from continuing to work on it as the sole author of it.

I'd ask for source code to be sure the software is safe to use, personally. That's the only reason I'd ask for it.  You can decline people making pull requests or telling you what they believe is best for the project, but to me, knowing there's no malicious code is the most important thing.

**Comment by rimpy-custom** [comment]
You are wrong on that. That means anyone is able to fork your code and republish it with changes. That situation may take a lot of efforts from me to "prove something to someone" while I dislike wasting my time on that. The code will be published when I feel it needs to be published.

**Comment by Ashturian** [comment]
I don't see how people creating forks of the code would affect you though? You don't have to spend any time on what other people do in order to keep working on your own branch, unless I'm missing something?

Either way, as its author, you're free to handle the source code as you wish. I'll just take your advice for the time being and wait until it can be audited.

Edit: Food for thought to anyone who might stumble across this, there's at least three people out there reporting malware in this software package. Might just be coincidence and infected by other sources, but take your safety into your own hands and run this responsibly if you do use it.

Software is only trustworthy when its code can be audited. Maybe this is free out of the goodness of the dev's heart, but if they aren't commercialising it, why keep it closed? There's zero reason not to open source this if there's nothing to hide.

**Comment by rimpy-custom** [comment]
That is what I was talking about. I see no reason to prove to you my vision of the situation. Keep safe.

**Comment by rimpy-custom** [comment]
Instead of creating a new comment, you decided to edit your old one with some speculations. That is exactly what I was talking about earlier when mentioned users that go mad when they do not receive what they asked for and do not want get other person's opinion. It is a pity that here that is starting again, but a good example and may answer on some questions that were asked by topic starter.

**Comment by Ashturian** [comment]
Brother, you haven't addressed a single point we've raised, you're just sitting there and preaching that we're mad. Sure it's speculation, but when three separate users find malware in a closed-source tool, I say a user has a duty to speculate.

You already gave all the opinion that we were gonna get: that you don't have to justify yourself to us. And you don't! But to be real I'd have trusted it more if you said you wanted to commercialise to protect your niche.

If you believe you've made your point then nothing more needs to be said, I already made mine.

**Comment by rimpy-custom** [comment]
No need to do that, I am not your brother. You are trying to give your opinion as the opinion of others in this topic. I said that users like you go mad, not others. Currently, only you tries to blame in that manner. I have told you my point of view of this situation. Instead of getting it, you read my message and edited yours two hours later with that abusive speculations That is called passive aggressivness. You may have your opinion, but do not express it like that and do not force others to do what you want.
Earlier I have mentioned that I do not like such conversations because they lead to nowhere. There is no valid reason that will satisfy you or users like you. Just stop this.

**Comment by MacSlash** [comment]
The owner giving no valid reason why they closed-source their program, only getting angry at people in an issue who are confused why you didn't open-source it and completely ignoring claims that that their code has malware in it with "it's only speculation", this is insanely funny btw and I'm genuinely dumbfounded this person is getting this mad about people online.

**Comment by rimpy-custom** [comment]
Because I do not have to explain anything. Nevertheless I am not going to hear baseless accusations. That is not fun to see that topic that started like "may you provide sources" is now "your software has malware"... because you do not want to provide sources... based on assumption that any closed source program has malware in it... Is that real? What answer do you expect to get after that?!

I have another "food for your mind", Do you recompile mod's dll's from sources when you get them from workshop? You cannot answer, since you are banned currently, but think about that.

**Comment by WilliamVenner** [comment]
Why would you close-source a RimWorld mod manager 💀

**Comment by rimpy-custom** [comment]
I didn't

**Comment by WilliamVenner** [comment]
Where's the code then? 🤔

**Comment by wingiu** [comment]
If they're going to complain about your wrong decisions and wrong code you can tell them to fuck off and replicate it "properly" since it's opensource :^)

**Comment by ISukONiA** [comment]
since Linux is a choice first, having your program as closed source is a perfectly valid choice

**Comment by rimpy-custom** [comment]
> Where's the code then? 🤔

idk

**Comment by rimpy-custom** [comment]
Is it possible to deny users reply in this issue but keep it active? Since that is going nowhere, I am gonna lock it but keep active.

**Comment by Matyas-Cerny** [comment]
Oh so now you're saying that he doesn't know where the source is. I'd wager to guess it's on your hard drive.

**Comment by rimpy-custom** [comment]
Oh, I found it

**Comment by rimpy-custom** [comment]
To all users that are going to post new messages in here. Issue is locked. All information is given above. Message that does not added new information and are too heated were deleted. Please, repsect others choice. Code will be published when I feel it is needed to be published.
